import re
import json

# Define the 72 campaigns
campaigns = []

# 1. Brandalism & Guerrilla (18)
brandalism_titles = [
    "Graffiti Viral", "Proyección Láser no Autorizada", "Hackeo de Vallas Publicitarias", "Stickers en Señales de Tráfico",
    "Flashmob Sorpresa", "Pancarta Gigante en Monumento", "Disfraces Infiltrados", "Falsos Titulares de Noticias",
    "Estatuas Vivas del Artista", "Invasión de Códigos QR", "Billetes Falsos Promocionales", "Cajas Misteriosas en Plazas",
    "Tatuajes Gratuitos para Fans", "Piratería Aprobada en Torrent", "Carteles Subversivos", "Hackeo de Altavoces Públicos",
    "Intervención Artística Urbana", "Boicot Falso (Autosabotaje)"
]

# 2. Branding & PR (18)
branding_titles = [
    "Diseño de Logotipo Minimalista", "Merchandising de Lujo", "Colaboración con Marca de Zapatos", "Documental 'Detrás de Escena'",
    "Alianza con Fundación Benéfica", "Campaña de Moda Urbana", "Creación de Personaje Alter-Ego", "Lanzamiento de Perfume",
    "Revista Exclusiva del Sello", "Gira Universitaria", "Cambio de Imagen Radical", "Membresía VIP para Fans",
    "Exposición de Arte del Álbum", "Cafetería Temática Pop-up", "Serie de Podcast Oficial", "Libro Autobiográfico",
    "Fiesta Secreta de Escucha", "Identidad Visual 3D"
]

# 3. Marketing Tradicional (Old School) (18)
old_school_titles = [
    "Anuncio en Revista Rolling Stone", "Valla Publicitaria en Times Square", "Comercial de TV en Prime Time", "Payola en Radios Locales",
    "Gira de Entrevistas de Radio", "Firma de Discos en Tiendas", "Pósteres en el Metro", "Anuncio en Periódico Nacional",
    "CDs Gratuitos en Revistas", "Publirreportaje de 2 páginas", "Patrocinio de Evento Deportivo", "Mención en Programa Nocturno",
    "Buzoneo (Flyers en casas)", "Campaña de Telemarketing", "Pegada de Carteles Nocturna", "Campaña de Relaciones Públicas Clásica",
    "Fiesta de Lanzamiento de Prensa", "Anuncio en MTV (o canal musical)"
]

# 4. Marketing Digital (New School) (18)
digital_titles = [
    "Trend de Baile en TikTok", "Juego de Realidad Alternativa (ARG)", "Filtro AR de Instagram", "Fuga 'Accidental' en Discord",
    "Marketing de Influencers (Tier 1)", "Concierto Virtual en Fortnite", "Campaña de Google Ads", "Sorteo de Entradas en Twitter",
    "Sesión de Reddit AMA", "Playlist Patrocinada en Spotify", "Shorts Virales en YouTube", "Campaña de Email Marketing",
    "Meme Marketing", "Adquisición de Página de Inicio en Twitch", "Reto de Covers en Reels", "NFTs Exclusivos para Fans",
    "Colaboración con Streamers", "Lanzamiento en Espacios de Twitter"
]

def generate_objs(titles, category, start_cost, cost_multiplier):
    objs = []
    for i, title in enumerate(titles):
        cost = start_cost + (i * cost_multiplier)
        effect = (cost // 1000) + 1
        days = (i % 5) + 2
        objs.append({
            "id": f"{category}_{i}",
            "title": title,
            "category": category,
            "cost": cost,
            "days": days,
            "effect": effect,
            "icon": "🎨" if category == "brandalism" else "💎" if category == "branding" else "📺" if category == "old_school" else "📱"
        })
    return objs

campaigns.extend(generate_objs(brandalism_titles, "brandalism", 500, 200))
campaigns.extend(generate_objs(branding_titles, "branding", 2000, 1000))
campaigns.extend(generate_objs(old_school_titles, "old_school", 5000, 2000))
campaigns.extend(generate_objs(digital_titles, "digital", 1000, 800))

campaigns_json = json.dumps(campaigns, ensure_ascii=False)

# Read HTML
with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace HTML section
new_html = """
                <!-- Marketing -->
                <section id="marketing" class="section hidden">
                    <h2 class="section-title">📢 Campañas de Promoción</h2>
                    <div style="margin-bottom: 20px; display: flex; gap: 10px; flex-wrap: wrap;">
                        <button class="btn btn-primary" onclick="renderMarketing('brandalism')">🎨 Brandalism</button>
                        <button class="btn btn-primary" onclick="renderMarketing('branding')">💎 Branding</button>
                        <button class="btn btn-primary" onclick="renderMarketing('old_school')">📺 Old School</button>
                        <button class="btn btn-primary" onclick="renderMarketing('digital')">📱 Digital</button>
                    </div>
                    <div class="actions-grid" id="marketingGrid">
                        <!-- Rendered by JS -->
                    </div>
                    <div class="market-chart" style="margin-top: 30px;">
                        <h3 style="margin-bottom: 20px;">📈 Reconocimiento de Marca</h3>
                        <div class="chart-container" id="brandChart">
                            <!-- Chart will be generated by JS -->
                        </div>
                    </div>
                </section>
"""

# Regex to find the whole marketing section and replace it
import re
pattern = re.compile(r'<!-- Marketing -->.*?<div class="market-chart"', re.DOTALL)
content = pattern.sub(new_html.split('<div class="market-chart"')[0] + '<div class="market-chart"', content)


# Replace JS marketing logic
old_js_pattern = re.compile(r'// === MARKETING ===.*?function generateInvestors', re.DOTALL)

new_js = f"""// === MARKETING ===
    const allCampaigns = {campaigns_json};
    let currentMarketingCategory = 'digital';

    function renderMarketing(category = null) {{
        if (category) currentMarketingCategory = category;
        const grid = document.getElementById('marketingGrid');
        const filtered = allCampaigns.filter(c => c.category === currentMarketingCategory);
        
        grid.innerHTML = filtered.map(c => `
            <div class="action-card" onclick="marketingCampaign('${{c.id}}')">
                <div class="action-icon">${{c.icon}}</div>
                <div class="action-title">${{c.title}}</div>
                <div class="action-desc">Aumenta reputación y exposición.</div>
                <div class="action-cost">
                    <span class="cost-item cost-money">💰 $${{c.cost.toLocaleString()}}</span>
                    <span class="cost-item cost-time">⏱️ ${{c.days}} días</span>
                </div>
            </div>
        `).join('');
    }}

    function marketingCampaign(id) {{
        const c = allCampaigns.find(camp => camp.id === id);
        if (!c) return;
        
        if (game.money < c.cost) return showNotification('¡Presupuesto insuficiente!', 'error');

        game.money -= c.cost;
        setTimeout(() => {{
            game.reputation += c.effect;
            game.brandAwareness.push(game.brandAwareness[game.brandAwareness.length - 1] + c.effect);
            if (game.brandAwareness.length > 7) game.brandAwareness.shift();
            addEvent(`¡La campaña '${{c.title}}' fue un éxito! Reputación +${{c.effect}}`);
            updateUI();
        }}, 100);

        addEvent(`Campaña lanzada: ${{c.title}} (${{c.days}} días)`);
        showNotification('¡Campaña lanzada!');
    }}

    function generateInvestors"""

content = old_js_pattern.sub(new_js, content)

# Make sure renderMarketing is called when showing section
# "if (sectionId === 'marketing') renderMarketing();"
if "if (sectionId === 'marketing') renderMarketing();" not in content:
    content = content.replace("if (sectionId === 'products') renderProducts();", "if (sectionId === 'products') renderProducts();\n        if (sectionId === 'marketing') renderMarketing();")


with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done")
