import json

recruits = []

def add_recruit(id, name, desc, role, skill, hireCost, salary):
    recruits.append({
        "id": id,
        "name": name,
        "desc": desc,
        "role": role,
        "skill": skill,
        "hireCost": hireCost,
        "salary": salary
    })

import random
random.seed(42)

roles_pool = ['developer', 'designer', 'manager', 'sales']

raw_recruits_data = [
    # 1-32: Chapter 1 (Governance, Love, 6 Virtues, Punishments, 9 Prohibitions)
    ("Centinela de la Benevolencia", "Entrenado en el fundamento de la benevolencia política de la dinastía antigua; prioriza la reconciliación y la paz interna.", "developer", 75, 1400, 2800),
    ("Guardia de la Rectitud", "Un comandante dispuesto a pacificar al pueblo y someter voluntariamente a las provincias mediante la rectitud.", "developer", 78, 1500, 3000),
    ("Oficial de la Sabiduría", "Estratega que comprende el fin y el inicio del combate, sirviendo como guía de conducta para las masas.", "developer", 82, 1700, 3400),
    ("Jefe del Coraje de Sima", "Soldado valiente que sabe cuándo indultar a los sometidos, aplicando el coraje sin crueldad innecesaria.", "developer", 80, 1600, 3200),
    ("Custodio de la Integridad", "Fiel protector que espera a que el enemigo complete su formación antes de iniciar el asalto en honor a la integridad.", "developer", 85, 1900, 3800),
    ("Sanador de Enemigos Heridos", "Médico de campaña instruido en el edicto del Primer Ministro: proporcionar atención médica a los heridos del enemigo y devolverlos.", "sales", 72, 1200, 2400),
    ("Protector de la Ancianidad", "Guardia perimetral que protege y escolta a los niños y ancianos del offender en concordancia con los antiguos ritos de la Xia.", "sales", 70, 1100, 2200),
    ("Pacificador de Templos", "Oficial que prohíbe violentar los templos y los dioses del territorio enemigo al entrar en su jurisdicción.", "manager", 76, 1300, 2600),
    ("Conservador del Bosque Sagrado", "Encargado de vigilar que las tropas no talen bosques ni destruyan obras de tierra en territorio enemigo.", "designer", 74, 1250, 2500),
    ("Inspector de Tributos y Ritos", "Inspector encargado de vigilar las aduanas y ritos de las cuatro esquinas del reino para evitar desvíos financieros.", "sales", 81, 1650, 3300),
    ("Ejecutor de las 9 Prohibiciones", "Oficial estricto que castiga a quienes encrochan tierras de estados débiles o desplazan a su población civil.", "developer", 83, 1800, 3600),
    ("Azote de Tiranos Bully", "Comandante de vanguardia asignado a purgar a los nobles brutales que abusan de sus subordinados.", "developer", 84, 1850, 3700),
    ("Restaurador de Tierras Agrícolas", "Agrónomo militar que castiga a quienes causan que los campos queden inutilizados y la población se disperse.", "sales", 75, 1350, 2700),
    ("Guerrero del Respeto Familiar", "Soldado jurado que persigue y castiga con la muerte a quienes asesinan a sus propios familiares consanguíneos.", "developer", 79, 1450, 2900),
    ("Vengador del Gobernante Digno", "Fuerza especial encargada de exterminar a los rebeldes que deponen o asesinan a su gobernante legítimo.", "manager", 86, 2100, 4200),
    ("Martillo de la Insurrección", "Zapador pesado que destruye las fortificaciones de los que desobedecen las órdenes del Soberano.", "designer", 88, 2200, 4400),
    ("Cazador de los Hombres-Animales", "Comandante implacable que extingue a las hordas corruptas y lujuriosas que actúan como bestias sin moral.", "developer", 82, 1750, 3500),
    ("Señor de la Forma y la Tierra", "Cartógrafo que define la geografía de los señores feudales mediante la distribución justa de territorios.", "manager", 77, 1400, 2800),
    ("Beduino de la Guía Silenciosa", "Explorador que lidera la caballería esquivando las tormentas de arena estacionales del mediodía.", "manager", 80, 1500, 3000),
    ("Maestre de Armaduras de la Xia", "Artesano que forja protecciones metálicas optimizadas para las tropas ligeras del desierto.", "designer", 79, 1380, 2760),
    ("Escriba del Mandato del Cielo", "Erudito que redacta edictos de paz y música para convencer a los estados extranjeros de someterse sin violencia.", "sales", 73, 1200, 2400),
    ("Vigía del Paso Estacional", "Observador que calcula los ciclos celestes para evitar movilizar al ejército en el invierno o el verano severo.", "manager", 78, 1300, 2600),
    ("Heraldo de la Campaña de Rectificación", "Mensajero veloz que anuncia las ofensas de los estados rebeldes a toda la nación antes de la marcha.", "sales", 74, 1150, 2300),
    ("Ingeniero de Esclusas Hidráulicas", "Especialista en desviar el flujo de agua para proteger Baghdad de inundaciones o asedios prolongados.", "designer", 83, 1700, 3400),
    ("Capitán del Langar Equitativo", "Oficial encargado de repartir las raciones de grano de forma equitativa para evitar motines de hambre.", "sales", 76, 1250, 2500),
    ("Guardián de la Moral de Sima", "Consejero espiritual que instruye a las tropas en las seis virtudes clásicas antes de salir a campaña.", "developer", 81, 1600, 3200),
    ("Explorador de Pozos Secos", "Guía del desierto que localiza e inutiliza los pozos de agua que el enemigo pretende usar.", "manager", 82, 1680, 3360),
    ("Oficial de la No Violencia", "Comandante que evita atacar estados en duelo o durante desastres naturales, respetando la moral cósmica.", "developer", 75, 1300, 2600),
    ("Soldado de la Paz Armónica", "Infantería que entona cantos tradicionales durante la marcha para disolver el pánico al asedio enemigo.", "developer", 73, 1100, 2200),
    ("Constructor del Campamento Humilde", "Carpintero de asedio que levanta tiendas perimetrales ordenadas para albergar a los refugiados del este.", "designer", 77, 1320, 2640),
    ("Sanador con Trinity de Raíces", "Asistente médico especializado en la cocción de jengibre y ajo para purificar la sangre de los infectados.", "sales", 74, 1180, 2360),
    ("Alquimista de Salitre y Cal", "Químico militar que prepara compuestos aglutinantes para sellar las murallas fracturadas por catapultas.", "designer", 84, 1750, 3500),

    # 33-64: Chapter 2 (Duty of Son of Heaven, Instruction, Chariots, Flags, Insignia, Order, Rewards/Punishments)
    ("Instructor de la Dignidad", "Oficial que instruye a los reclutas en la distinción de rangos para evitar fricciones y desórdenes.", "developer", 76, 1250, 2500),
    ("Comandante del Yuan Rong", "Piloto experto del carro de guerra Yuan Rong, valorado por su inmensa fuerza estructural en el choque.", "designer", 85, 1850, 3700),
    ("Jefe del Carro de Gancho", "Conductor del carro de gancho de la dinastía Xia, famoso por su suave de desplazamiento en la arena.", "designer", 80, 1500, 3000),
    ("Piloto del Carro Yin", "Conductor del veloz carro Yin de la dinastía Shang, optimizado para cargas tácticas de alta velocidad.", "designer", 82, 1600, 3200),
    ("Abanderado de la Bandera Negra", "Portador de la insignia negra de la Xia, que representa la guía suprema del líder de los hombres.", "developer", 77, 1300, 2600),
    ("Abanderado de la Bandera Blanca", "Portador de la insignia blanca de la Shang, que simboliza la justicia del cielo en el campo de batalla.", "developer", 79, 1400, 2800),
    ("Abanderado de la Bandera Amarilla", "Portador de la insignia amarilla de la Zhou, que manifiesta la verdad del camino de la Tierra.", "developer", 81, 1500, 3000),
    ("Custodio del Sol y la Luna", "Oficial que porta la insignia luminosa del sol y la luna, guiando a la vanguardia en la penumbra.", "manager", 83, 1750, 3500),
    ("Portador de la Insignia del Tigre", "Guerrero pesado que porta el emblema del tigre, infundiendo awesomeness y pavor en las legiones romanas.", "developer", 84, 1800, 3600),
    ("Portador del Dragón de Zhou", "Oficial que porta el emblema del dragón, inspirando cultura, disciplina y fe en los defensores.", "developer", 85, 1900, 3800),
    ("Centinela de la Casa de la Sabiduría", "Guardia jurado asignado a la Casa de la Sabiduría para proteger los manuscritos antiguos de incendios.", "manager", 78, 1400, 2800),
    ("Maestre del Tambor del Caballo", "Músico de guerra que dirige el paso y el aliento de los corceles de caballería ligera.", "designer", 75, 1200, 2400),
    ("Maestre del Tambor del Carro", "Percusionista de vanguardia que coordina las cargas y giros de los carros pesados de asedio.", "designer", 76, 1250, 2500),
    ("Maestre del Tambor de Infantería", "Músico que marca el compás de la marcha síncrona para evitar que los lanceros rompan filas.", "developer", 74, 1150, 2300),
    ("Ejecutor de Oaths de Xia", "Oficial que administra los juramentos sagrados dentro del campamento para elevar el espíritu combativo.", "sales", 78, 1300, 2600),
    ("Heraldo del Juramento de Zhou", "Orador que proclama los edictos de Zhou justo antes del choque de espadas para motivar a las masas.", "sales", 80, 1450, 2900),
    ("Herrero del Acero de Damasco", "Artesano que forja espadas y lanzas equilibradas, asegurando que no sean ni muy largas ni muy cortas.", "designer", 84, 1800, 3600),
    ("Oficial de la No Jactancia", "Militar humilde y de gran talento que no presume de sus logros, garantizando informes verídicos de campaña.", "developer", 86, 2000, 4000),
    ("Escriba de la Deferencia de Rango", "Contable militar que registra las hazañas de combate sin generar arrogancia entre los oficiales superiores.", "sales", 77, 1350, 2700),
    ("Guardia de la Deferencia de Derrota", "Oficial que en caso de derrota asume la responsabilidad junto con el comandante, evitando recriminaciones.", "developer", 80, 1500, 3000),
    ("Oficial de la Justicia Inmediata", "Ejecutor de recompensas y castigos rápidos para mantener la credibilidad de la ley sin demoras.", "developer", 82, 1650, 3300),
    ("Arquero de la Calma Pránica", "Tirador de élite entrenado en regular su respiración bajo el estruendo de los proyectiles enemigos.", "designer", 83, 1700, 3400),
    ("Espía de la Infiltración Civil", "Agente infiltrado en las plazas públicas para evaluar el descontento popular y las conspiraciones.", "manager", 81, 1600, 3200),
    ("Explorador de los Caminos de Tierra", "Rastreador que busca senderos libres de la caballería pesada y puestos avanzados enemigos.", "manager", 82, 1680, 3360),
    ("Oficial de la Magnanimidad en Letrinas", "Sanitario militar que desinfecta campamentos y previene brotes de cólera y disentería.", "sales", 75, 1200, 2400),
    ("Maestre de Campanas de Parada", "Militar encargado de hacer sonar las campanas de bronce para ordenar el repliegue ordenado de tropas.", "designer", 74, 1100, 2200),
    ("Diseñador de Escudos Scutum Falsos", "Artesano que fabrica escudos de imitación para desorientar a los arqueros enemigos sobre nuestras líneas.", "designer", 79, 1300, 2600),
    ("Especialista en Abrojos Metálicos", "Zapador ligero que siembra clavos en los valles estrechos para frenar el avance de las botas romanas.", "designer", 82, 1550, 3100),
    ("Oficial del Silencio Absoluto", "Comandante que dirige emboscadas silenciosas prohibiendo el uso de antorchas y voces de mando.", "developer", 83, 1750, 3500),
    ("Guía de la Retirada del Desierto", "Conductor experto que lidera la retirada del convoy por desfiladeros de difícil acceso para la legión.", "manager", 84, 1800, 3600),
    ("Negociador beduino de la Trinidad", "Delegado diplomático que convence a los beduinos de no guiar a los cartógrafos de Roma por el desierto.", "sales", 82, 1650, 3300),
    ("Lector de Astrología Militar", "Sabio que lee el movimiento de las estrellas para predecir tormentas de arena propicias para el ataque.", "manager", 76, 1200, 2400),

    # 65-98: Chapter 3 (Planning, Considerations, Unity, Disastrous Campaigns, 7 Affairs, 4 Controls)
    ("Estratega del Acordar con el Cielo", "Planificador que utiliza los cambios climáticos repentinos y la neblina para iniciar emboscadas.", "developer", 84, 1900, 3800),
    ("Oficial de Acumulación por Sequestro", "Especialista en requisar raciones y trigo del campamento enemigo para abastecer nuestras despensas.", "sales", 80, 1500, 3000),
    ("Comandante del Placer del Pueblo", "Líder que solo inicia campañas militares que gozan de la aprobación moral y el fervor de la población.", "developer", 81, 1600, 3200),
    ("Defensor de Puntos Estratégicos", "Oficial de infantería pesada experto en la defensa de cañones y pasos angostos en la frontera.", "developer", 83, 1750, 3500),
    ("Instructor del Arco y la Flecha", "Maestre que entrena a los reclutas en el uso de arcos compuestos para repeler asaltos a gran distancia.", "designer", 78, 1300, 2600),
    ("Maestre de la Maza y la Lanza", "Entrenador en combate cerrado para defender las puertas principales contra el ariete romano.", "designer", 79, 1350, 2700),
    ("Especialista en Alabardas Apoyadas", "Infantería de élite armada con alabardas largas para sostener la línea frente a cargas montadas.", "designer", 82, 1600, 3200),
    ("Copiador de Nuevas Armas", "Ingeniero metalúrgico que analiza y replica las armas de asedio romanas capturadas en combate.", "designer", 85, 1950, 3900),
    ("Analista de Ventajas y Ganancias", "Financiero militar que evalúa el costo-beneficio de cada incursión antes de movilizar los camellos.", "sales", 82, 1600, 3200),
    ("Ordenador del Caos Urbano", "Oficial de policía militar que impone el orden civil en las calles de Baghdad bajo fuego de catapultas.", "developer", 80, 1450, 2900),
    ("Regulador del Avance y Parada", "Heraldo que transmite las órdenes de avance y parada mediante banderas reflectantes de bronce.", "sales", 76, 1200, 2400),
    ("Aceptador de Remonstrancias", "General de mente abierta que escucha los consejos de sus subalternos para evitar campañas desastrosas.", "developer", 86, 2050, 4100),
    ("Nutridor del Sentido de Vergüenza", "Instructor que forja el pundonor en los reclutas para que prefieran la muerte honorable antes que la deserción.", "developer", 78, 1300, 2600),
    ("Simplificador de Leyes de Sima", "Escriba que reduce el código militar a reglas sencillas de entender para evitar confusiones gástricas.", "sales", 75, 1180, 2360),
    ("Vigilante de Ofensas Menores", "Oficial de disciplina que castiga las faltas pequeñas para evitar que las tropas cometan crímenes mayores.", "developer", 79, 1400, 2800),
    ("Divinador de la Caparazón de Tortuga", "Sacerdote que realiza lecturas en caparazones para elegir en secreto el día propicio del ataque.", "manager", 77, 1250, 2500),
    ("Maestre del Secreto Militar", "Oficial que coordina las operaciones encubiertas en silencio absoluto para evitar el espionaje de Roma.", "manager", 85, 1900, 3800),
    ("Administrador de la Riqueza del Estado", "Tesorero que asegura que los recursos de Baghdad se mantengan abundantes antes de declarar la guerra.", "sales", 84, 1800, 3600),
    ("Entrenador de Formaciones Flexibles", "Comandante que instruye a las tropas en cambiar de formación dispersa a cerrada en segundos.", "developer", 83, 1700, 3400),
    ("Planificador del Foreseeable", "Estratega que analiza los riesgos futuros de la campaña y prepara raciones de frijol mung de reserva.", "developer", 85, 1950, 3900),
    ("Oficial de Con concordia de Chariots", "Coordinador de movimientos que asegura la sincronización entre la caballería y la infantería ligera.", "designer", 80, 1450, 2900),
    ("Neutralizador de la Arrogancia Extrema", "Oficial de moral encargado de calmar las actitudes soberbias de los comandantes veteranos del este.", "developer", 82, 1600, 3200),
    ("Cazador de la Laxitud de Guardia", "Inspector que vigila que los centinelas nocturnos mantengan el estado de alerta sin caer en la somnolencia.", "manager", 80, 1480, 2960),
    ("Espía del Sabotaje Interno", "Agente enviado al campamento enemigo para sembrar rumores de peste entre sus tropas auxiliares.", "manager", 86, 2100, 4200),
    ("Observador del Terreno Cercano", "Explorador que analiza los valles secos cercanos a las murallas para sembrar trampas de foso.", "manager", 81, 1500, 3000),
    ("Abonador del Fervor de Rectitud", "Predicador militar que estimula la moral de los soldados recordándoles su deber con el Creador.", "developer", 83, 1700, 3400),
    ("Jefe del Control Centralizado", "Oficial que asume el mando unificado cuando los métodos tradicionales de defensa fallan en el caos.", "developer", 87, 2250, 4500),
    ("Oficial del Vestir por Protocolo", "Encargado de la uniformidad militar para mantener la distinción visual de los rangos en batalla.", "sales", 73, 1100, 2200),
    ("Administrador de los Cuatro Controles", "Magistrado militar que gestiona la gloria, el lucro, la vergüenza y la muerte para mantener el orden.", "developer", 84, 1800, 3600),
    ("Maestre de la Batalla Marina", "Ingeniero naval encargado de fortificar las barcazas del río Tigris para resistir ataques fluviales.", "designer", 81, 1550, 3100),
    ("Especialista en Tácticas de Fuego", "Zapador de asedio que diseña compuestos de brea y azufre para quemar las arietes romanas.", "designer", 85, 1900, 3800),
    ("Guardián de la Fe del Langar", "Cocinero militar consagrado que entona cantos sagrados sobre las raciones de basmati de los heridos.", "sales", 76, 1200, 2400),
    ("Espía de la Retaguardia Romana", "Infiltrado en las cocinas del César que sabotea la carne salada enemiga introduciendo ricino.", "manager", 87, 2150, 4300),
    ("Negociador de la Alianza Beduina", "Embajador que recluta a los jefes nómadas para que actúen como la caballería de choque de Baghdad.", "sales", 83, 1700, 3400),

    # 99-130: Chapter 4 (Troop Requirements, Sitting/Squatting, Endurance, Respect, Causes of Death, Drums)
    ("Oficial de la Calma en Cuclillas", "Comandante que entrena a la infantería a mantener la posición en cuclillas para resistir el bombardeo.", "developer", 80, 1400, 2800),
    ("Lanzador de Abrojos de Templo", "Zapador de defensa que protege los templos sembrando abrojos metálicos en sus entradas.", "designer", 78, 1300, 2600),
    ("Diseñador de la Defensa Estática", "Arquitecto que diseña barricadas móviles de madera y espinas para canalizar la caballería romana.", "designer", 82, 1600, 3200),
    ("Capitán del Tambor de Standing", "Músico de guerra que coordina el levantamiento y repliegue de los lanceros con ritmos de tambor.", "developer", 75, 1150, 2300),
    ("Ejecutor de Deserción Inmediata", "Oficial de justicia que ejecuta sumariamente a los desertores en fuga para evitar el pánico colectivo.", "developer", 84, 1800, 3600),
    ("Comandante del Vigor Magnánimo", "Líder que no castiga a las tropas asustadas por el ariete, sino que les muestra el camino a la victoria.", "developer", 83, 1750, 3500),
    ("Regulador de la Comida del Ejército", "Oficial de logística que prohíbe cortar las raciones de alimento como forma de castigo militar.", "sales", 77, 1250, 2500),
    ("Custodio de los Confines del Sueño", "Inspector médico que vigila que las guardias de los soldados no excedan un solo ciclo de descanso.", "sales", 76, 1200, 2400),
    ("Oficial de la Tensión del Escudo", "Comandante de infantería que calma el miedo de sus soldados ordenando asumir la posición de sentados.", "developer", 81, 1500, 3000),
    ("Guerrero del Desapego de la Muerte", "Lancero entrenado en entender que el cuerpo físico es temporal, combatiendo sin pánico a la espada.", "developer", 85, 1900, 3800),
    ("Sanador del Prana Capilar", "Masajista militar que estimula la columna vertebral de los guerreros para aliviar la fatiga muscular.", "sales", 74, 1100, 2200),
    ("Alquimista de los Vientos de Baghdad", "Especialista en lanzar polvos irritantes al aire aprovechando la dirección de las corrientes de viento.", "designer", 83, 1700, 3400),
    ("Constructor de Trincheras de Arena", "Zapador civil que excava trincheras profundas en la arena fina para atrapar las caligae de los romanos.", "designer", 79, 1300, 2600),
    ("Oficial del Silbato de Arcilla", "Vigía que utiliza silbatos de alta frecuencia para desorientar a los caballos de guerra enemigos.", "manager", 78, 1250, 2500),
    ("Espía de la Cisterna Sagrada", "Guardia jurado que custodia los filtros de carbón vegetal y arena del pozo principal de la ciudad.", "manager", 82, 1600, 3200),
    ("Negociador del Trigo del Este", "Comerciante que escolta las caravanas de grano del este, asegurando el sustento del Langar.", "sales", 81, 1500, 3000),
    ("Capitán del Tambor del Caballo", "Músico de guerra que dirige el galope de los caballos ligeros de Baghdad con toques de tambor de cuero.", "designer", 76, 1200, 2400),
    ("Capitán del Tambor de la Infantería", "Percusionista que coordina el avance de la infantería a paso firme para mantener la formación cerrada.", "developer", 75, 1180, 2360),
    ("Maestre del Tambor del Avance del Carro", "Percusionista que indica el momento preciso para acelerar las ruedas de los carros de asalto.", "designer", 78, 1300, 2600),
    ("Maestre del Tambor de la Victoria", "Músico que entona las melodías de triunfo y rest del pueblo al culminar con éxito la campaña.", "sales", 74, 1100, 2200),
    ("Oficial de la Sincronía del Latido", "Comandante que unifica la mente de sus hombres mediante cantos colectivos antes de la batalla.", "developer", 82, 1600, 3200),
    ("Guerrero del Amor y la Gratitud", "Soldado de vanguardia dispuesto a dar la vida por gratitud al Langar y a la protección de Baghdad.", "developer", 83, 1700, 3400),
    ("Guerrero de la Ira de la Trinidad", "Infantería pesada estimulada con ajo y jengibre, liberando una gran fuerza en la melé de vanguardia.", "developer", 81, 1550, 3100),
    ("Guerrero del Deber Sagrado", "Soldado jurado que combate exclusivamente por justicia moral y desapego de los bienes terrenales.", "developer", 85, 1950, 3900),
    ("Coordinador del Uniforme Ligero", "Intendente que suministra ropajes livianos de lino a las tropas para maximizar su agilidad táctica.", "sales", 72, 1050, 2100),
    ("Oficial del Uniforme Stalwart", "Intendente que equipa a los defensores del muro con corazas reforzadas de cuero y bronce pulido.", "sales", 75, 1200, 2400),
    ("Maestre de la Honda de Arcilla", "Tirador experto que utiliza proyectiles esféricos de arcilla secada al sol para hostigar sin sangre.", "designer", 80, 1400, 2800),
    ("Vigía del Alerta de Espejos", "Operador de señales que reporta movimientos de caballería romana desde el alminar más alto.", "manager", 81, 1450, 2900),
    ("Zapador de la Contramina Elevada", "Minero que excava galerías subterráneas para colapsar las minas de asedio del campamento romano.", "designer", 84, 1850, 3700),
    ("Oficial de la Guerra Psicológica", "Orador que proyecta sombras gigantescas sobre las murallas para inducir paranoia en los vigías enemigos.", "manager", 82, 1600, 3200),
    ("Recolector de la Cosecha del Oasis", "Líder de brigada civil que recolecta dátiles y cebada al amanecer bajo el amparo de la neblina.", "sales", 78, 1300, 2600),
    ("Estratega del Yunque y el Martillo", "General que coordina el envolvimiento de las legiones enemigas mediante cargas coordinadas de flanco.", "developer", 86, 2100, 4200),

    # 131-162: Chapter 5 (Large vs Small forces, Tactics, Wind, Mountains, Chasing, Cities, letters forbidden, rest)
    ("Comandante del Cerco Abierto", "Estratega experto en rodear fuerzas enemigas a distancia, dejando siempre una salida falsa para emboscarlos.", "developer", 84, 1850, 3700),
    ("Defensor de la Duna del Viento", "Soldado de vanguardia entrenado en combatir manteniendo el viento del desierto siempre a sus espaldas.", "developer", 80, 1400, 2800),
    ("Oficial del Cañón del Desfiladero", "Lancero experto en defender pasos confinados manteniendo las alturas de piedra siempre a su derecha.", "developer", 83, 1700, 3400),
    ("Explorador de los Caminos de Lodo", "Rastreador que guía al convoy de grano esquivando las zonas pantanosas y los caminos rotos.", "manager", 79, 1350, 2700),
    ("Constructor del Campamento Tortuga", "Carpintero militar que levanta empalizadas configuradas en forma de caparazón de tortuga para resistir onagros.", "designer", 81, 1500, 3000),
    ("Observador del Alza de Masas", "Vigía que analiza los movimientos de la infantería romana, indicando el momento en que sus filas avanzan.", "manager", 82, 1580, 3160),
    ("Cazador de la Incertidumbre Romana", "Comandante de caballería que asalta los puestos de avanzada cuando nota dudas o divisiones en sus filas.", "developer", 83, 1750, 3500),
    ("Señuelo del Falso Repliegue", "Jinete ligero que finge huir abandonando su estandarte para tentar al enemigo a romper su formación.", "manager", 84, 1800, 3600),
    ("Contraatacador de la Persecución", "Líder que gira sutilmente a sus tropas para golpear en los flancos al enemigo que los persigue fatigado.", "developer", 85, 1900, 3800),
    ("Asaltante de la Muralla Ciega", "Zapador de asalto que ataca las secciones desprotegidas del campamento enemigo cuando están de espaldas.", "designer", 86, 2000, 4000),
    ("Infiltrado de la Red Nocturna", "Agente que corta las comunicaciones entre las cohortes romanas y su servicio de correo imperial.", "manager", 87, 2150, 4300),
    ("Oficial del Prohibido Escribir", "Censor militar que prohíbe la correspondencia familiar para concentrar la mente de las tropas en Baghdad.", "sales", 73, 1100, 2200),
    ("Intendente de Raciones Mínimas", "Distribuidor de suministros que equipa a los asaltantes con raciones ultraligeras para marchas rápidas.", "sales", 75, 1250, 2500),
    ("Despojador de Armaduras Pesadas", "Comando ligero que abandona su propia armadura pesada para maximizar su agilidad táctica en el desierto.", "designer", 82, 1600, 3200),
    ("Instructor de la Vigilancia Cíclica", "Oficial que organiza los turnos de guardia fronteriza para que no excedan media jornada de luz.", "developer", 78, 1350, 2700),
    ("Vigía de la Duna Silenciosa", "Observador que permanece inmóvil y cubierto en la arena para detectar exploradores enemigos.", "manager", 79, 1300, 2600),
    ("Saboteador de las Ruedas de Bronce", "Infiltrado que quita los pasadores de los carros de asedio enemigos en la oscuridad de la noche.", "designer", 83, 1700, 3400),
    ("Lancero de la Calma en Muralla", "Defensor del muro que resiste el asalto de las escalas romanas manteniendo la pica firme en silencio.", "developer", 81, 1450, 2900),
    ("Negociador del Trato de Dátiles", "Mercader que consigue suministros de dátiles y cebada de los oasis del sur a cambio de sal de Baghdad.", "sales", 80, 1400, 2800),
    ("Portador de la Bandera de la Tierra", "Oficial que guía al convoy militar portando la bandera amarilla, símbolo del camino de la Tierra de Zhou.", "developer", 78, 1300, 2600),
    ("Maestre de la Carga de Caballería", "Líder de jinetes que realiza cargas parabólicas rápidas sobre la infantería enemiga dispersa.", "developer", 85, 1850, 3700),
    ("Sanador del Caldo Inmunológico", "Cocinero del campamento de sanación que prepara caldos de jengibre y ajo para restaurar la moral y el prana.", "sales", 77, 1200, 2400),
    ("Operador de Códigos Lumínicos", "Encargado de los reflectores de bronce pulido, comunicando alertas fronterizas a los cañones del este.", "manager", 82, 1500, 3000),
    ("Excavador de la Galería Doble", "Minero que refuerza las galerías de contramina subterránea con dobles muros de ladrillo refractario.", "designer", 83, 1750, 3500),
    ("Oficial de la Perturbación de Sombras", "Operador de linternas en los muros que simula el movimiento de grandes divisiones militares en la noche.", "manager", 81, 1480, 2960),
    ("Recolector del Amanecer Sagrado", "Brigadista que cosecha trigo y lentejas en las huertas urbanas antes del primer avistamiento del César.", "sales", 76, 1200, 2400),
    ("Estratega del Paso Angosto", "Comandante que embosca y anula la fuerza numérica de una legión entera de 5,000 hombres en una quebrada.", "developer", 87, 2200, 4400),
    ("Instructor de Formaciones en Cuclillas", "Oficial de adiestramiento que entrena a los lanceros jóvenes en la flexión y empuje síncrono.", "developer", 78, 1250, 2500),
    ("Constructor del Foso de Ariete", "Ingeniero que profundiza los fosos defensivos perimetrales frente a las puertas principales de Baghdad.", "designer", 84, 1800, 3600),
    ("Saboteador de Cuerdas de Onagro", "Infiltrado pirómano que corta e incendia los tensores de torsión de la artillería romana pesada.", "designer", 85, 1950, 3900),
    ("Cazador de Jinetes Decumanos", "Arquero montado especializado en cazar a los mensajeros a caballo del correo militar romano.", "manager", 83, 1700, 3400),
    ("Escolta del Trigo del Este", "Lancero perimetral que defiende a los camellos de carga de las caravanas de trigo de los ataques de bandidos.", "sales", 80, 1450, 2900)
]

for idx, item in enumerate(raw_recruits_data):
    add_recruit(f"rec_{idx+1}", item[0], item[1], item[2], item[3], item[4], item[5])

js_content = "const allRecruits = " + json.dumps(recruits, ensure_ascii=False, indent=4) + ";"
with open('recruits_data.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print("recruits_data.js creado exitosamente. Total reclutas:", len(recruits))
